package FundamentalJava.TipeDataPrimitif;

import java.util.Scanner;

/**
 * Booleans (Logika)
 * Tipe data boolean hanya memiliki dua nilai: true atau false.
 * Tipe ini digunakan untuk logika dan mengontrol pernyataan bersyarat seperti if dan for.
 * Sederhana, hanya ada dua: true dan false. Keduanya tidak memiliki representasi numerik.
 */ 

public class Boolean {
    public static void main(String[] args) {

        /**
         * Tipe Data boolean
         * Ekspresi yang hasilnya cuma bisa salah (false) atau benar (true)
         * disebut ekspresi logis atau ekspresi boolean.
         * Komputer itu bikin keputusan berdasarkan ekspresi logis ini.
         *
         * Tipe data boolean punya dua nilai saja: false dan true.
         * boolean, false, dan true adalah kata kunci (reserved words).
         * Memori yang dialokasikan untuk tipe data boolean adalah 1 bit.
         *
         * Note 2.7: Nilai boolean false tidak sama dengan bilangan bulat 0, dan nilai boolean true tidak sama dengan 1.
         * Oleh karena itu, nilai boolean tidak bisa menjadi bagian dari ekspresi aritmatika (penjumlahan,
         * pengurangan, perkalian, dll.).
         *
         * kita juga bisa langsung mengisi variabel boolean dengan hasil dari sebuah ekspresi logika.
         * ini adalah cara yg ringkas dan disarankan.
         *
         * Poin-poin penting tentang boolean.
         * - jangan gunakan if statement yang panjang hanya untuk mengsisi variabel boolean
         * - jangan membandingkan boolean dengan true atau false. nilai true atau false tidak punya nilai numerik.
         *   jadi gak bisa pakai operator relational <,>
         *   tapi bisa pakai operator kesetaraan ==, !=. namun membandingkan variabel boolean dengan true atau false aalah
         *   redudant (mengulang).
         */

        boolean b;
        b = false;
        System.out.println("b is " + b);
        b = true;
        System.out.println("b is " + b);

        // a boolean value can control the if statement
        if (b) System.out.println("This is executed.");
        b = false;
        if(b) System.out.println("This is not executed.");

        // outcome of a relational operator is a boolean value
        System.out.println("10 > 9 is " + (10 > 9));

        /**
         * The output generated by this program is shown here:
         *  b is false
         *  b is true
         *  This is executed.
         *  10 > 9 is true
         *
         * There are three interesting things to notice about this program. First, as you can see,
         * when a boolean value is output by println( ), "true" or "false" is displayed. Second, the value
         * of a boolean variable is sufficient, by itself, to control the if statement. There is no need to
         * write an if statement like this:
         * if(b == true) …
         * Third, the outcome of a relational operator, such as <, is a boolean value. This is why the
         * expression 10>9 displays the value "true." Further, the extra set of parentheses around 10>9
         * is necessary because the + operator has a higher precedence than the >.
         */

        boolean thisBoolean;
        int number;
        Scanner inputUser = new Scanner(System.in);

        System.out.print("Masukkan Angka: ");
        System.out.flush();
        number = inputUser.nextInt();

        if (number > 0) System.out.println("Angka Positif (Plus)");
        if (number < 0) System.out.println("Angka Negatif (Minus)");
        inputUser.close();

        // jangan gunakan if statement yang panjang hanya untuk mengsisi variabel boolean
        char charOne = 'q';
        boolean isLowerCaseLetter;

        // ini cara yang buruk dan bertele-tele
        if ('a' <= charOne && charOne <= 'z')
            isLowerCaseLetter = true;
        else
            isLowerCaseLetter = false;

        System.out.println(isLowerCaseLetter);

        // cara yang baik (ringkas dan langsung)
        // cukup pakai 1 baris kode.
        isLowerCaseLetter = ('a' <= charOne && charOne <= 'z');
        System.out.println(isLowerCaseLetter);
    }
}
